### ISSUE TITLE
Convert the Knative properties to immutable properties in deployment

### ISSUE THREAD

**Issue by ricardozanini** [apache/incubator-kie-kogito-serverless-operator#371]
### Description

This work depends on the completion of the task of Immutable env var for the properties ([SRVLOGIC-195](https://issues.redhat.com/browse/SRVLOGIC-195)  and [SRVLOGIC-196](https://issues.redhat.com/browse/SRVLOGIC-196))

currently, all the properties(application.properties) are preserved and reconciled in the workflow's configmap.  once the immutable properties are converted to env var config in deployment. we should have the corresponding update for knative related properties

**Comment by jianrongzhang89** [comment]
Will look into this issue.

**Comment by jianrongzhang89** [comment]
1) Tested [sonataflow with event time out](https://gist.github.com/jianrongzhang89/d26a22e863ec677696889a06a7644d8e) successfully. The sonataflow event has 'kind' set to produced.
Confirmed that a sinkbinding is created, and the knative related properties are included in the immutable managed configmap:`callbackstatetimeouts-managed-props`:
    mp.messaging.outgoing.kogito_outgoing_stream.connector = quarkus-http
    mp.messaging.outgoing.kogito_outgoing_stream.url = ${K_SINK}
    org.kie.kogito.addons.knative.eventing.health-enabled = true

2) Tested [sonataflow with greeting] (https://gist.github.com/jianrongzhang89/b8d437eac99124edf5e5c9c72581c747) successfully. It has an onEvent configured so that external cloud events are sent to the workflow via the broker.
Confirmed that a trigger is created, and the knative related properties are included in the immutable managed configmap `greeting-managed-props`:
    mp.messaging.incoming.kogito_incoming_stream.connector = quarkus-http
    mp.messaging.incoming.kogito_incoming_stream.path = /extra/path
    org.kie.kogito.addons.knative.eventing.health-enabled = true

So this functionality works as expected.
