### ISSUE TITLE
Create a Prometheus `ServiceMonitor` object that can capture/collect metrics from deployed `SonataFlow` instances

### ISSUE THREAD

**Issue by ricardozanini** [apache/incubator-kie-kogito-serverless-operator#464]
### Description

The operator can track in the cluster if Prometheus Operator is installed. If this condition is true and the `SonataFlowPlatform` is marked with `.spec.monitoring: true`, then each workflow instance can have a [`ServiceMonitor`](https://prometheus-operator.dev/docs/operator/design/#servicemonitor) object bound to it.

### Implementation ideas

Each `SonataFlow` already exposes a `Service`. Hence, in this issue, it's expected that each `ServiceMonitor` instance binds to it.

Verify with `kogito-runtimes` the endpoints to scrap for metrics (should be `/metrics`).

### Prereqs

- Prometheus operator is installed
- `Prometheus` CR is already deployed and configured in the cluster. The operator **won't provision** a Prometheus server.

**Comment by jianrongzhang89** [comment]
We decided to modify the scope for this issue so that the operator only creates a service monitor for workflows deployed as k8s deployments. A separate issue has been created to track the work for workflows deployed as Knative services: 
https://github.com/apache/incubator-kie-kogito-serverless-operator/issues/550
